server:
  port: ${SERVER_PORT:8080}
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  data:
    redis:
      connect-timeout: 2000
      host: 127.0.0.1
      port: 6379
    mongodb:
      database: ${DATABASE_NAME:personal-db}
      uri: ${DATABASE_URI:mongodb://test:test@localhost:27017/?retryWrites=true&w=majority}